
SELECT SALES_VIEW_V2.GENRE as GENRE, 
ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE, 
SALES_VIEW_V2.STORE_ID as STORE_ID, ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE_1, 
ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE_1_1, 
COUNT(SALES_VIEW_V2.SALE_DATE) as SALE_DATE FROM SALES_VIEW_V2 
WHERE  (SALE_DATE >= '2011-02-11') AND (SALE_DATE <= '2012-03-01') GROUP BY GENRE, STORE_ID
UNION

SELECT SALES_VIEW_V2.GENRE as GENRE, 
ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE, STORE_ID = null, ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE_1, 
ROUND(SUM(SALES_VIEW_V2.PRODUCT_PRICE),2) as PRODUCT_PRICE_1_1, 
COUNT(SALES_VIEW_V2.SALE_DATE) as SALE_DATE FROM SALES_VIEW_V2 
WHERE  (SALE_DATE >= '2011-02-11') AND (SALE_DATE <= '2012-03-01') GROUP BY GENRE